backend:
  name: github
  repo: Softwire/strawberry-fair
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "frontend/src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: home-page}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
  - name: "about-page"
    label: "About"
    folder: "frontend/src/pages/about-pages/"
    create: true
    fields:
      - {label: "Template Key", name: templateKey, widget: hidden, default: blog-post}
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
      - {label: Image, name: image, widget: image}
