backend:
  name: github
  repo: Softwire/strawberry-fair
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "frontend/src/pages/home/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: home-page}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
