backend:
  name: github
  repo: Softwire/strawberry-fair
  branch: sf-17
  commit_messages:
    create: Netlify CMS - Create {{collection}} “{{slug}}”
    update: Netlify CMS - Update {{collection}} “{{slug}}”
    delete: Netlify CMS - Delete {{collection}} “{{slug}}”
    uploadMedia: Netlify CMS - Upload “{{path}}”
    deleteMedia: Netlify CMS - Delete “{{path}}”

media_folder: /frontend/static/img
public_folder: /img


## ACCESSIBLE IMAGE TEMPLATE ##
## 
##          - label: Image
##            name: ximage
##            widget: object
##            fields:
##              - {label: Description, name: alt, widget: string}
##              - {label: Image, name: src, widget: image}


collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "frontend/src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: home-page}
          - {label: Title, name: title, widget: string}
          - label: Banner
            name: revolvingHero
            widget: object
            fields:
              - label: Image 1
                name: image1
                widget: object
                fields:
                  - {label: Description, name: alt, widget: string}
                  - {label: Image, name: src, widget: image}
              - label: Image 2
                name: image2
                widget: object
                fields:
                  - {label: Description, name: alt, widget: string}
                  - {label: Image, name: src, widget: image}
              - label: Image 3
                name: image3
                widget: object
                fields:
                  - {label: Description, name: alt, widget: string}
                  - {label: Image, name: src, widget: image}
              - label: Image 4
                name: image4
                widget: object
                fields:
                  - {label: Description, name: alt, widget: string}
                  - {label: Image, name: src, widget: image}
              - label: Image 5
                name: image5
                widget: object
                fields:
                  - {label: Description, name: alt, widget: string}
                  - {label: Image, name: src, widget: image}
          - {label: Body, name: body, widget: markdown}
      - file: "frontend/src/pages/news/index.md"
        label: "News Home"
        name: "news-home"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: news-overview}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
  - name: "news"
    label: "News Articles"
    folder: "frontend/src/pages/news/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: templateKey, widget: hidden, default: news-article}
      - {label: Title, name: title, widget: string}
      - {label: Author, name: author, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Body, name: body, widget: markdown}
      - {label: Date, name: date, widget: datetime, format: YYYY-MM-DD, dateFormat: YYYY-MM-DD, timeFormat: false}
      - {label: Tags, name: tags, widget: list, default: ["news"]}
  - name: "events"
    label: "Events"
    folder: "frontend/src/pages/events/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Will need to figure out the syntax to change this, because what if
    fields:                                     # you have two events on the same day?
      - {label: "Template Key", name: templateKey, widget: hidden, default: event-info}
      - {label: Title, name: title, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Date, name: dateTime, widget: datetime}
      - {label: Meeting, name: isMeeting, widget: boolean}
      - {label: Body, name: body, widget: markdown}
  - name: "about"
    label: "About"
    folder: "frontend/src/pages/about/"
    create: true
    fields:
      - {label: "Template Key", name: templateKey, widget: hidden, default: about-page}
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Body, name: body, widget: markdown}
